[unstable]
#build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
#build-std-features = ["compiler-builtins-mem"]

[build]
#target = "x86_64-unknown-linux-gnu"
#target = "aarch64-apple-darwin"
#target = "x86_64-unknown-uefi"
#rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
